import type { ChristianModeContent, ChristianSessionMode, ChristianVerse } from './types';

const universalVerses: ChristianVerse[] = [
  {
    id: 'daily-psalm-23-1',
    title: 'The Lord Is My Shepherd',
    reference: 'Psalm 23:1',
    text: 'The Lord is my shepherd; I shall not want.',
    theme: 'Peace',
    mode: 'universal',
  },
  {
    id: 'daily-matthew-11-28',
    title: 'Come Unto Me',
    reference: 'Matthew 11:28',
    text: 'Come unto me, all ye that labour and are heavy laden, and I will give you rest.',
    theme: 'Rest',
    mode: 'universal',
  },
  {
    id: 'daily-lamentations-3-22-23',
    title: 'Mercies Every Morning',
    reference: 'Lamentations 3:22-23',
    text: 'His compassions fail not. They are new every morning: great is thy faithfulness.',
    theme: 'Renewal',
    mode: 'universal',
  },
  {
    id: 'daily-philippians-4-6-7',
    title: 'Peace Beyond Understanding',
    reference: 'Philippians 4:6-7',
    text: 'The peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.',
    theme: 'Peace',
    mode: 'universal',
  },
  {
    id: 'daily-isaiah-40-31',
    title: 'Strength Renewed',
    reference: 'Isaiah 40:31',
    text: 'They that wait upon the Lord shall renew their strength.',
    theme: 'Strength',
    mode: 'universal',
  },
  {
    id: 'daily-1-thessalonians-5-18',
    title: 'Give Thanks',
    reference: '1 Thessalonians 5:18',
    text: 'In every thing give thanks: for this is the will of God in Christ Jesus concerning you.',
    theme: 'Gratitude',
    mode: 'universal',
  },
  {
    id: 'daily-psalm-46-10',
    title: 'Be Still',
    reference: 'Psalm 46:10',
    text: 'Be still, and know that I am God.',
    theme: 'Stillness',
    mode: 'universal',
  },
];

export const CHRISTIAN_DAILY_VERSES = universalVerses;

export const CHRISTIAN_MODE_CONTENT: Record<ChristianSessionMode, ChristianModeContent> = {
  dailyScripture: {
    mode: 'dailyScripture',
    title: 'Daily Scripture',
    subtitle: 'Arrive softly and let today’s verse lead the prayer.',
    description: 'A scripture-centered session shaped by quiet reading, reflection, and prayer.',
    setupPrompt: 'Choose a gentle pace and let the verse become your prayer corner for today.',
    arrivalPrompt: 'Set the phone down gently. Let your attention arrive before your words do.',
    scriptureIntro: 'Read slowly. Let a single phrase stay with you and gather your attention.',
    reflectionPrompt: 'What word or phrase is inviting you to stay a little longer with God today?',
    stillnessPrompt: 'Breathe softly and let the verse echo in the quiet.',
    blessing:
      'May the word of Christ dwell richly in you, guiding your thoughts and steadying your day.',
    journalPrompt: 'What stayed with you from today’s scripture?',
    tags: ['scripture', 'quiet', 'daily'],
    suggestedDuration: 5,
    heroVerse: universalVerses[0],
    prayerPrompts: {
      praise: 'Jesus, I praise You for speaking before I know what to say.',
      confession: 'Forgive the places where I rushed past Your voice or relied on my own noise.',
      thanksgiving: 'Thank You for meeting me through scripture with patience and mercy.',
      intercession: 'Let this word bring life to the people and places I carry with me.',
      surrender: 'I release this day to You. Let Your word settle deeper than my worry.',
    },
  },
  guidedPrayer: {
    mode: 'guidedPrayer',
    title: 'Guided Prayer',
    subtitle: 'Move through praise, confession, thanks, intercession, and surrender.',
    description: 'A balanced liturgy for when you want structure without pressure.',
    setupPrompt: 'Choose a duration that gives space for the whole movement of prayer.',
    arrivalPrompt: 'Arrive with open hands. Nothing needs to be polished before God.',
    scriptureIntro: 'Let this verse frame the whole prayer with steadiness and trust.',
    reflectionPrompt: 'What part of your life most needs honest prayer rather than quick answers?',
    stillnessPrompt: 'Rest between each movement and notice where peace begins to grow.',
    blessing:
      'May the grace of Christ keep you near, truthful in prayer, and peaceful in the next step.',
    journalPrompt: 'Which movement of prayer felt most needed today?',
    tags: ['guided', 'balanced', 'prayer'],
    suggestedDuration: 10,
    heroVerse: {
      id: 'guided-colossians-4-2',
      title: 'Continue in Prayer',
      reference: 'Colossians 4:2',
      text: 'Continue in prayer, and watch in the same with thanksgiving.',
      theme: 'Guided Prayer',
      mode: 'guidedPrayer',
    },
    prayerPrompts: {
      praise: 'Lord, You are faithful, steady, and more present than my distractions.',
      confession: 'I confess the ways I have carried my own strength instead of coming to You.',
      thanksgiving: 'Thank You for staying close with mercy I did not have to earn.',
      intercession: 'Receive the names and needs I carry. Cover them with Your kindness.',
      surrender: 'I place what I cannot control into Your hands and ask for calm obedience.',
    },
  },
  peace: {
    mode: 'peace',
    title: 'Prayer For Peace',
    subtitle: 'A warm, steadying flow for anxious thoughts and crowded hearts.',
    description: 'For moments of unrest, fear, and emotional noise.',
    setupPrompt: 'Settle into a slower pace and let the prayer corner become a place of rest.',
    arrivalPrompt: 'Let your shoulders soften. You do not need to hold everything right now.',
    scriptureIntro: 'Receive this promise rather than trying to solve the whole day at once.',
    reflectionPrompt: 'What fear or burden most needs the peace of Christ right now?',
    stillnessPrompt: 'Breathe in peace. Breathe out what you no longer need to grip.',
    blessing:
      'May the peace of Christ keep your heart, quiet your mind, and follow you into the next hour.',
    journalPrompt: 'What burden felt lighter after prayer?',
    tags: ['peace', 'anxiety', 'rest'],
    suggestedDuration: 5,
    heroVerse: {
      id: 'peace-john-14-27',
      title: 'Peace I Leave With You',
      reference: 'John 14:27',
      text: 'Peace I leave with you, my peace I give unto you: let not your heart be troubled, neither let it be afraid.',
      theme: 'Peace',
      mode: 'peace',
    },
    prayerPrompts: {
      praise: 'Prince of Peace, I praise You for being calm where I am unsettled.',
      confession: 'Forgive the places where fear has become louder than trust.',
      thanksgiving: 'Thank You for staying near even when my thoughts are restless.',
      intercession: 'Carry peace to the people and situations that feel most fragile today.',
      surrender: 'I release my fear, my urgency, and my need to manage everything alone.',
    },
  },
  strength: {
    mode: 'strength',
    title: 'Prayer For Strength',
    subtitle: 'A reverent session for resilience, courage, and faithful endurance.',
    description: 'For weariness, pressure, and the need to keep going with grace.',
    setupPrompt: 'Choose a duration that gives you room to breathe and recover.',
    arrivalPrompt: 'Bring your fatigue honestly. God does not need you to look strong first.',
    scriptureIntro: 'Let this promise meet the exact place where you feel thin.',
    reflectionPrompt: 'Where do you need strength that is deeper than determination?',
    stillnessPrompt: 'Stay long enough for your breathing to become prayer.',
    blessing:
      'May the Lord renew your strength, steady your body, and give courage for faithful work.',
    journalPrompt: 'What kind of strength do you need most tomorrow?',
    tags: ['strength', 'courage', 'renewal'],
    suggestedDuration: 10,
    heroVerse: {
      id: 'strength-isaiah-40-31',
      title: 'Renew Their Strength',
      reference: 'Isaiah 40:31',
      text: 'They that wait upon the Lord shall renew their strength.',
      theme: 'Strength',
      mode: 'strength',
    },
    prayerPrompts: {
      praise: 'Lord, You remain steady when I feel depleted.',
      confession: 'Forgive the ways I have confused striving with faithfulness.',
      thanksgiving: 'Thank You for mercy that meets me even in weakness.',
      intercession:
        'Strengthen those who are weary, sick, discouraged, or carrying hidden burdens.',
      surrender: 'I entrust my limits to You and receive the grace for one faithful step.',
    },
  },
  gratitude: {
    mode: 'gratitude',
    title: 'Prayer Of Gratitude',
    subtitle: 'A radiant session of remembrance, thanks, and gentle joy.',
    description: 'For savoring grace, daily gifts, and God’s quiet kindness.',
    setupPrompt: 'Choose a gentle pace and let thankfulness become spacious, not rushed.',
    arrivalPrompt: 'Notice one gift already present before the prayer even begins.',
    scriptureIntro: 'Read this with an open memory and let the day’s mercies come forward.',
    reflectionPrompt: 'Which gift or mercy from today most clearly reminds you of God’s care?',
    stillnessPrompt: 'Hold one mercy in the quiet and let thanks move deeper than words.',
    blessing:
      'May gratitude make you attentive to grace, generous in spirit, and peaceful in heart.',
    journalPrompt: 'What mercy do you want to remember from today?',
    tags: ['gratitude', 'thanks', 'joy'],
    suggestedDuration: 5,
    heroVerse: {
      id: 'gratitude-psalm-107-1',
      title: 'Give Thanks Unto The Lord',
      reference: 'Psalm 107:1',
      text: 'O give thanks unto the Lord, for he is good: for his mercy endureth for ever.',
      theme: 'Gratitude',
      mode: 'gratitude',
    },
    prayerPrompts: {
      praise: 'Father, I praise You for goodness that keeps finding me in ordinary hours.',
      confession: 'Forgive the ways I have hurried past mercy without noticing it.',
      thanksgiving: 'Thank You for provision, breath, kindness, and unseen protection.',
      intercession: 'Let Your goodness comfort those who need a sign of hope today.',
      surrender: 'I release my scarcity and receive today as a gift held inside Your care.',
    },
  },
  eveningReflection: {
    mode: 'eveningReflection',
    title: 'Evening Reflection',
    subtitle: 'Close the day with honesty, mercy, and quiet release.',
    description: 'For dusk, examen-style prayer, and peaceful completion.',
    setupPrompt: 'Choose a slower duration and let the day settle before sleep.',
    arrivalPrompt: 'The day is already in God’s hands. You are only arriving to notice it.',
    scriptureIntro: 'Read this as a lamp for the evening, not as another demand.',
    reflectionPrompt: 'Where did you notice grace today, and where do you still need mercy?',
    stillnessPrompt: 'Exhale the unfinished day and rest in the care of Christ.',
    blessing:
      'May Christ keep watch through the night, give rest to your body, and peace to your thoughts.',
    journalPrompt: 'What do you want to release before sleep?',
    tags: ['evening', 'examen', 'rest'],
    suggestedDuration: 15,
    heroVerse: {
      id: 'evening-psalm-4-8',
      title: 'Lie Down In Peace',
      reference: 'Psalm 4:8',
      text: 'I will both lay me down in peace, and sleep: for thou, Lord, only makest me dwell in safety.',
      theme: 'Evening Reflection',
      mode: 'eveningReflection',
    },
    prayerPrompts: {
      praise: 'Lord, I praise You for holding this day from beginning to end.',
      confession: 'Forgive my impatience, my divided attention, and the ways I withheld love.',
      thanksgiving: 'Thank You for mercies seen and unseen across these ordinary hours.',
      intercession: 'Watch over the people I love and those I cannot help from here.',
      surrender: 'I release the unfinished day, my regrets, and tomorrow’s weight into Your care.',
    },
  },
};
