import type { Chant } from './types';

export const CHANTS: Chant[] = [
  {
    id: 'namo-tassa',
    slug: 'namo-tassa',
    title: 'Namo Tassa',
    titleThai: 'นโม ตัสสะ',
    subtitle: 'Homage to the Buddha',
    category: 'daily',
    durationSeconds: 120,
    difficulty: 'beginner',
    purpose: 'Begin every prayer session with homage to the Blessed One',
    verses: [
      {
        id: 'namo-1',
        order: 1,
        pali: 'Namo tassa bhagavato arahato sammā-sambuddhassa',
        thai: 'นโม ตัสสะ ภะคะวะโต อะระหะโต สัมมาสัมพุทธัสสะ',
        english: 'Homage to the Blessed One, the Worthy One, the Rightly Self-Awakened One',
        transliteration: 'Namo tassa bhagavato arahato sammā-sambuddhassa',
        meaning:
          'We pay homage to the Buddha, who is fully enlightened, free from defilements, and worthy of our deepest respect.',
      },
      {
        id: 'namo-2',
        order: 2,
        pali: 'Namo tassa bhagavato arahato sammā-sambuddhassa',
        thai: 'นโม ตัสสะ ภะคะวะโต อะระหะโต สัมมาสัมพุทธัสสะ',
        english: 'Homage to the Blessed One, the Worthy One, the Rightly Self-Awakened One',
        transliteration: 'Namo tassa bhagavato arahato sammā-sambuddhassa',
        meaning: 'We pay homage a second time, deepening our reverence and intention.',
      },
      {
        id: 'namo-3',
        order: 3,
        pali: 'Namo tassa bhagavato arahato sammā-sambuddhassa',
        thai: 'นโม ตัสสะ ภะคะวะโต อะระหะโต สัมมาสัมพุทธัสสะ',
        english: 'Homage to the Blessed One, the Worthy One, the Rightly Self-Awakened One',
        transliteration: 'Namo tassa bhagavato arahato sammā-sambuddhassa',
        meaning:
          'We pay homage a third time, completing the traditional threefold offering of respect.',
      },
    ],
  },
  {
    id: 'itipiso',
    slug: 'itipiso',
    title: 'Itipiso',
    titleThai: 'อิติปิโส',
    subtitle: 'Virtues of the Triple Gem',
    category: 'daily',
    durationSeconds: 240,
    difficulty: 'intermediate',
    purpose: 'Reflect on the qualities of the Buddha, Dhamma, and Sangha',
    verses: [
      {
        id: 'itipiso-1',
        order: 1,
        pali: 'Itipi so bhagavā arahaṃ sammāsambuddho',
        thai: 'อิติปิ โส ภะคะวา อะระหัง สัมมาสัมพุทโธ',
        english: 'The Blessed One is indeed worthy and fully self-awakened',
        transliteration: 'Itipi so bhagavā arahaṃ sammāsambuddho',
        meaning:
          'The Buddha is worthy of offerings and has attained supreme enlightenment through his own effort.',
      },
      {
        id: 'itipiso-2',
        order: 2,
        pali: 'Vijjācaraṇasampanno sugato lokavidū',
        thai: 'วิชชาจะระณะสัมปันโน สุคะโต โลกะวิทู',
        english: 'Accomplished in knowledge and conduct, the Well-Gone, the Knower of the world',
        transliteration: 'Vijjācaraṇasampanno sugato lokavidū',
        meaning:
          'The Buddha possesses perfect wisdom and conduct, has traveled the noble path, and understands all worlds completely.',
      },
      {
        id: 'itipiso-3',
        order: 3,
        pali: 'Anuttaro purisadammasārathi satthā devamanussānaṃ buddho bhagavāti',
        thai: 'อะนุตตะโร ปุริสะทัมมะสาระถิ สัตถา เทวะมะนุสสานัง พุทโธ ภะคะวาติ',
        english:
          'The peerless trainer of persons to be tamed, teacher of gods and humans, the Buddha, the Blessed One',
        transliteration: 'Anuttaro purisadammasārathi satthā devamanussānaṃ buddho bhagavāti',
        meaning:
          'The Buddha is the unsurpassed guide, the teacher of both gods and humans, fully awakened and blessed.',
      },
    ],
  },
  {
    id: 'triple-gem',
    slug: 'triple-gem',
    title: 'Triple Gem Refuge',
    titleThai: 'ไตรสรณคมน์',
    subtitle: 'Taking Refuge in the Three Jewels',
    category: 'daily',
    durationSeconds: 180,
    difficulty: 'beginner',
    purpose: 'Establish spiritual protection and orientation through the Three Jewels',
    verses: [
      {
        id: 'gem-1',
        order: 1,
        pali: 'Buddhaṃ saraṇaṃ gacchāmi',
        thai: 'พุทธัง สะระณัง คัจฉามิ',
        english: 'I go to the Buddha for refuge',
        transliteration: 'Buddhaṃ saraṇaṃ gacchāmi',
        meaning:
          'I seek protection and guidance in the Buddha — the awakened one who shows the path to liberation.',
      },
      {
        id: 'gem-2',
        order: 2,
        pali: 'Dhammaṃ saraṇaṃ gacchāmi',
        thai: 'ธัมมัง สะระณัง คัจฉามิ',
        english: 'I go to the Dhamma for refuge',
        transliteration: 'Dhammaṃ saraṇaṃ gacchāmi',
        meaning: 'I seek refuge in the Dhamma — the teachings and the truth of the way things are.',
      },
      {
        id: 'gem-3',
        order: 3,
        pali: 'Saṅghaṃ saraṇaṃ gacchāmi',
        thai: 'สังฆัง สะระณัง คัจฉามิ',
        english: 'I go to the Sangha for refuge',
        transliteration: 'Saṅghaṃ saraṇaṃ gacchāmi',
        meaning:
          'I seek refuge in the Sangha — the community of those who practice and embody the teachings.',
      },
      {
        id: 'gem-4',
        order: 4,
        pali: 'Dutiyampi buddhaṃ saraṇaṃ gacchāmi',
        thai: 'ทุติยัมปิ พุทธัง สะระณัง คัจฉามิ',
        english: 'For the second time, I go to the Buddha for refuge',
        transliteration: 'Dutiyampi buddhaṃ saraṇaṃ gacchāmi',
        meaning: 'We deepen our commitment by taking refuge again.',
      },
      {
        id: 'gem-5',
        order: 5,
        pali: 'Dutiyampi dhammaṃ saraṇaṃ gacchāmi',
        thai: 'ทุติยัมปิ ธัมมัง สะระณัง คัจฉามิ',
        english: 'For the second time, I go to the Dhamma for refuge',
        transliteration: 'Dutiyampi dhammaṃ saraṇaṃ gacchāmi',
        meaning: 'We renew our commitment to the teachings.',
      },
      {
        id: 'gem-6',
        order: 6,
        pali: 'Dutiyampi saṅghaṃ saraṇaṃ gacchāmi',
        thai: 'ทุติยัมปิ สังฆัง สะระณัง คัจฉามิ',
        english: 'For the second time, I go to the Sangha for refuge',
        transliteration: 'Dutiyampi saṅghaṃ saraṇaṃ gacchāmi',
        meaning: 'We renew our connection to the community of practitioners.',
      },
    ],
  },
  {
    id: 'merit-dedication',
    slug: 'merit-dedication',
    title: 'Merit Dedication',
    titleThai: 'อุทิศกุศล',
    subtitle: 'Sharing the Merit of Practice',
    category: 'merit-making',
    durationSeconds: 90,
    difficulty: 'beginner',
    purpose: 'Dedicate the merit of your practice to the wellbeing of all beings',
    verses: [
      {
        id: 'merit-1',
        order: 1,
        pali: 'Idaṃ me ñātinaṃ hotu, sukhitā hontu ñātayo',
        thai: 'อิทัง เม ญาตีนัง โหตุ สุขิตา โหนตุ ญาตะโย',
        english: 'May this merit be for my relatives. May my relatives be happy.',
        transliteration: 'Idaṃ me ñātinaṃ hotu, sukhitā hontu ñātayo',
        meaning:
          'We share the merit of our practice with our family and relatives, wishing them peace and happiness.',
      },
      {
        id: 'merit-2',
        order: 2,
        pali: 'Sabbe sattā sukhitā hontu',
        thai: 'สัพเพ สัตตา สุขิตา โหนตุ',
        english: 'May all beings be happy',
        transliteration: 'Sabbe sattā sukhitā hontu',
        meaning: 'We extend our wish for happiness to all living beings, without exception.',
      },
    ],
  },
  {
    id: 'metta-sutta',
    slug: 'metta-sutta',
    title: 'Metta Sutta',
    titleThai: 'เมตตาสูตร',
    subtitle: 'Loving-Kindness Prayer',
    category: 'daily',
    durationSeconds: 300,
    difficulty: 'beginner',
    purpose: 'Cultivate loving-kindness and compassion for all beings',
    verses: [
      {
        id: 'metta-1',
        order: 1,
        pali: 'Karaṇīyam atthakusalena',
        thai: 'กะระณียะมัตถะกุสะเลนะ',
        english: 'This is what should be done by one who is skilled in goodness',
        transliteration: 'Karaṇīyam atthakusalena',
        meaning:
          'The Buddha outlines what a person of good will should do to cultivate the path of loving-kindness.',
      },
      {
        id: 'metta-2',
        order: 2,
        pali: 'Sabbe sattā sukhī hontu, sabbe sattā averā hontu',
        thai: 'สัพเพ สัตตา สุขี โหนตุ สัพเพ สัตตา อะเวรา โหนตุ',
        english: 'May all beings be happy. May all beings be free from enmity.',
        transliteration: 'Sabbe sattā sukhī hontu, sabbe sattā averā hontu',
        meaning:
          'We wish genuine happiness and freedom from hostility for every being in existence.',
      },
      {
        id: 'metta-3',
        order: 3,
        pali: 'Sabbe sattā abyāpajjhā hontu, sabbe sattā anīghā hontu',
        thai: 'สัพเพ สัตตา อัพยาปัชฌา โหนตุ สัพเพ สัตตา อะนีฆา โหนตุ',
        english: 'May all beings be free from ill will. May all beings be free from suffering.',
        transliteration: 'Sabbe sattā abyāpajjhā hontu, sabbe sattā anīghā hontu',
        meaning:
          'We wish freedom from mental distress and physical suffering for all beings everywhere.',
      },
    ],
  },
];

export const CHANT_CATEGORIES = [
  { id: 'daily' as const, label: 'Daily', description: 'Chants for everyday practice' },
  { id: 'merit-making' as const, label: 'Merit Making', description: 'Dedicate merit to others' },
  { id: 'ceremonial' as const, label: 'Ceremonial', description: 'Special occasion chants' },
  { id: 'learning' as const, label: 'Learning', description: 'Study the meanings' },
];
