name: Publish preview update

on:
  push:
    branches: ['*']

jobs:
  publish_preview_update:
    name: Publish preview update
    environment: preview
    type: update
    params:
      branch: ${{ github.ref_name || 'test' }}
